# Generated by Django 4.1.1 on 2022-09-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OteviraciDoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den_od', models.PositiveSmallIntegerField(choices=[(0, 'pondělí'), (1, 'úterý'), (2, 'středa'), (3, 'čtvrtek'), (4, 'pátek'), (5, 'sobota'), (6, 'neděle')])),
                ('den_do', models.PositiveSmallIntegerField(choices=[(0, 'pondělí'), (1, 'úterý'), (2, 'středa'), (3, 'čtvrtek'), (4, 'pátek'), (5, 'sobota'), (6, 'neděle')])),
                ('cas_od', models.TimeField()),
                ('cas_do', models.TimeField(choices=[(0, 'pondělí'), (1, 'úterý'), (2, 'středa'), (3, 'čtvrtek'), (4, 'pátek'), (5, 'sobota'), (6, 'neděle')])),
            ],
        ),
        migrations.CreateModel(
            name='ProdejniMisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interni_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('typ', models.CharField(max_length=20)),
                ('nazev', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
            ],
        ),
    ]
