# Generated by Django 4.1.1 on 2022-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodejnimisto',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prodejnimisto',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
