# Generated by Django 4.1.1 on 2022-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid', '0002_prodejnimisto_lat_prodejnimisto_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodejnimisto',
            name='otviraci_doby',
            field=models.ManyToManyField(blank=True, to='pid.oteviracidoba'),
        ),
        migrations.AlterField(
            model_name='oteviracidoba',
            name='cas_do',
            field=models.TimeField(),
        ),
    ]
